### ISSUE TITLE
Assigning invalid time in reduce crashes the runtime

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle#359]
```
$ bin/juttle -e 'emit -limit 1 | reduce time = 1'
Unhandled rejection RuntimeError: Invalid type assigned to time: number (1).
    at Object.runtimeError (/Users/dmajda/Jut/Code/juttle/lib/errors.js:73:12)
    at Object.errors.typeErrorTime (/Users/dmajda/Jut/Code/juttle/lib/runtime/errors.js:55:29)
    at oops_funcs.emit (/Users/dmajda/Jut/Code/juttle/lib/runtime/procs/oops_funcs.js:30:38)
    at /Users/dmajda/Jut/Code/juttle/lib/runtime/procs/reduce.js:254:26
    at tryCatcher (/Users/dmajda/Jut/Code/juttle/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/Users/dmajda/Jut/Code/juttle/node_modules/bluebird/js/main/method.js:31:24)
    at /Users/dmajda/Jut/Code/juttle/lib/runtime/procs/reduce.js:253:35
    at tryCatcher (/Users/dmajda/Jut/Code/juttle/node_modules/bluebird/js/main/util.js:26:23)
    at ReductionPromiseArray._promiseFulfilled (/Users/dmajda/Jut/Code/juttle/node_modules/bluebird/js/main/reduce.js:105:38)
    at ReductionPromiseArray.init (/Users/dmajda/Jut/Code/juttle/node_modules/bluebird/js/main/promise_array.js:92:18)
    at ReductionPromiseArray.init (/Users/dmajda/Jut/Code/juttle/node_modules/bluebird/js/main/reduce.js:42:10)
    at Async._drainQueue (/Users/dmajda/Jut/Code/juttle/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/dmajda/Jut/Code/juttle/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dmajda/Jut/Code/juttle/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The expected behavior is dropping the point and producing a warning.

**Comment by dmajda** [comment]
Closed via #360.
