### ISSUE TITLE
Flaky parser/grok tests

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle#403]
I get the following failure intermittently on my local machine with Node.js 4.2.4:

```
  1) parsers/grok stops emitting values after the optimization.limit:

      AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at test/adapters/parsers/grok.spec.js:125:42
      at bound (domain.js:287:14)
      at runBound (domain.js:300:12)
      at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:581:18)
      at Promise._settlePromises (node_modules/bluebird/js/main/promise.js:697:14)
      at Async._drainQueue (node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/main/async.js:15:14)



[14:03:55] 'test' errored after 1.3 min
[14:03:55] Error in plugin 'gulp-mocha'
Message:
    1 test failed.
```

**Comment by dmajda** [comment]
@rlgomes Any idea what the cause might be?

**Comment by rlgomes** [comment]
assigning to myself will look into this.
