### ISSUE TITLE
Date parsing defaults to 2001 year

### ISSUE THREAD

**Issue by rlgomes** [juttle/juttle#452]
This happens when doing something like parsing syslog lines which don't have a year like so:

```
> echo 'Feb 24 07:58:53 x230 anacron[11982]: Job `cron.daily` terminated' | ./bin/juttle -e "read stdio -format 'grok' -pattern '%{SYSLOGLINE}' -timeField 'timestamp'"
┌────────────────────────────────────┬──────────────┬─────────────────────────────────────────┬──────────┬───────────┐
│ time                               │ logsource    │ message                                 │ pid      │ program   │
├────────────────────────────────────┼──────────────┼─────────────────────────────────────────┼──────────┼───────────┤
│ 2001-02-24T15:58:53.000Z           │ x230         │ Job `cron.daily` terminated             │ 11982    │ anacron   │
└────────────────────────────────────┴──────────────┴─────────────────────────────────────────┴──────────┴───────────┘
```

You can also see the same problem when doing Date.new() although you do get a nasty warning from the moment.js library:

```
> ./bin/juttle -e 'emit -limit 1 | put time=Date.new("Feb 24 00:00:00")'
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (/home/rlgomes/jut/workspace/juttle/node_modules/moment/moment.js:850:105)
    at configFromString (/home/rlgomes/jut/workspace/juttle/node_modules/moment/moment.js:970:32)
    at configFromInput (/home/rlgomes/jut/workspace/juttle/node_modules/moment/moment.js:1473:13)
    at prepareConfig (/home/rlgomes/jut/workspace/juttle/node_modules/moment/moment.js:1456:13)
    at createFromConfig (/home/rlgomes/jut/workspace/juttle/node_modules/moment/moment.js:1423:44)
    at createLocalOrUTC (/home/rlgomes/jut/workspace/juttle/node_modules/moment/moment.js:1505:16)
    at Function.create_utc__createUTC [as utc] (/home/rlgomes/jut/workspace/juttle/node_modules/moment/moment.js:64:16)
    at JuttleMoment.parseDate (/home/rlgomes/jut/workspace/juttle/lib/runtime/types/juttle-moment.js:116:30)
    at new JuttleMoment (/home/rlgomes/jut/workspace/juttle/lib/runtime/types/juttle-moment.js:70:18)
    at date.new (/home/rlgomes/jut/workspace/juttle/lib/runtime/modules/date.js:89:20)
    at /home/rlgomes/jut/workspace/juttle/lib/runtime/ops.js:289:23
    at Object.locate (/home/rlgomes/jut/workspace/juttle/lib/errors.js:95:16)
    at Object.ops.call (/home/rlgomes/jut/workspace/juttle/lib/runtime/ops.js:288:29)
    at juttle.procs.put.expr (eval at _eval (/home/rlgomes/jut/workspace/juttle/lib/program.js:36:26), <anonymous>:6:25)
    at /home/rlgomes/jut/workspace/juttle/lib/runtime/procs/put.js:72:25
    at Object.locate (/home/rlgomes/jut/workspace/juttle/lib/errors.js:95:16)
┌────────────────────────────────────┐
│ time                               │
├────────────────────────────────────┤
│ 2001-02-24T00:00:00.000Z           │
└────────────────────────────────────┘
```

This basically stems from the behavior of v8's `new Date()` defaulting to 2001 when no year is specified in a date. We'd want to possibly have our own ability to set the default and at the minimum to make it the current year since that would most likely be the best guess for a date missing a year.

**Comment by dmajda** [comment]
To repeat what I said in an internal discussion: We need some fuzzy parsing but at the same time, `new Date` heuristics differ engine from engine, so it might actually be a good idea to have our own set of heuristics & accepted formats in order to be independent on that.
