### ISSUE TITLE
Field deference operator test failing

### ISSUE THREAD

**Issue by mstemm** [juttle/juttle#525]
While working on a PR for changes to the http adapter, I noticed a probably unrelated test failure:

https://travis-ci.org/juttle/juttle/jobs/113442473

```1) Field dereference operator ambiguity Parses toplevel * as field dereference with whitespace before and no whitespace after:
      AssertionError: expected [ { count: 61 } ] to deeply equal [ { count: 62 } ]
      + expected - actual
       [
         {
      -    "count": 61
      +    "count": 62
         }
       ]
      
      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at test/runtime/specs/juttle-spec/parser/field-dereference-operator-ambiguity.spec.js:40:50
      at bound (domain.js:287:14)
      at runBound (domain.js:300:12)
      at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:581:18)
      at Async._drainQueue (node_modules/bluebird/js/main/async.js:128:12)
      at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/main/async.js:15:14)```

When manually re-running the test it passed, so I'd guess it's nondeterministic.

**Comment by dmajda** [comment]
@bkutil Could you have a look?

**Comment by bkutil** [comment]
Sure.
