### ISSUE TITLE
error in join after reduce -every

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#538]
Joining the output of `reduce -every` produces marks with no timestamps that are dropped and then crashes:

```
emit -from :0: -limit 10
| (
    reduce -every :5s: max(time);
    reduce -every :5s: min(time);
   )
| join
| view text -format 'raw' -times true

Error: Cannot read property 'gt' of undefined [TypeError: Cannot read property 'gt' of undefined]
Error: Cannot read property 'gt' of undefined [TypeError: Cannot read property 'gt' of undefined]
Error: Cannot read property 'gt' of undefined [TypeError: Cannot read property 'gt' of undefined]
Error: Cannot read property 'gt' of undefined [TypeError: Cannot read property 'gt' of undefined]
Error: Cannot read property 'gt' of undefined [TypeError: Cannot read property 'gt' of undefined]
Error: Cannot read property 'gt' of undefined [TypeError: Cannot read property 'gt' of undefined]
/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/join.js:774
        if (time.gt(this.last_mark)) {
                ^

TypeError: Cannot read property 'gt' of undefined
    at join.maybe_emit_mark (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/join.js:774:17)
    at join.emit_result (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/join.js:761:18)
    at join.advance_input (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/join.js:597:18)
    at join.mark_from (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/join.js:366:14)
    at join.consume_mark (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/join.js:349:14)
    at reduce_every.emit_mark (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/base.js:216:25)
    at reduce_every.emit_mark (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/oops-fanin.js:59:35)
    at reduce_every.periodic_eof (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/reduce.js:339:18)
    at reduce_every.eof (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/periodic-fanin.js:181:18)
    at reduce_every.consume_eof (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/fanin.js:94:18)
    at emit_eof (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/base.js:228:25)
    at emit.run (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/emit.js:186:18)
    at Object.callback (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/procs/emit.js:171:27)
    at Scheduler._run (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/scheduler.js:32:30)
    at null._onTimeout (/usr/local/lib/node_modules/juttle-engine/node_modules/juttle-service/node_modules/juttle/lib/runtime/scheduler.js:41:51)
    at Timer.listOnTimeout (timers.js:92:15)
```

This is likely related to #537 since it works fine if I change the `reduce -every` to `batch..reduce`.

**Comment by bkutil** [comment]
No longer reproducible with #543
