### ISSUE TITLE
Error: "Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by KrishnaPG** [juttle/juttle#666]
Fresh installation of juttle using below command, on window 10, nodejs v5.8.0 and npm@3.7.3

```
\Workspace>juttle -e "emit -limit 2 | put message='hello'"
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:494:7)
    at Object.<anonymous> (\AppData\Roaming\npm\node_modules\juttle-engine\node_modules\juttle-service\node_modules\juttle\bin\juttle:89:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (\AppData\Roaming\npm\node_modules\juttle-engine\node_modules\juttle-service\bin\juttle:10:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

The version command works, though: 

```
\Workspace>juttle --version
0.7.1
```

juttle was installed with `npm install -g juttle-engine` command.

**Comment by manish-ongithub** [comment]
I received same error on windows machine.
I installed it on a linux VM. It worked fine.
