### ISSUE TITLE
Standardize config.json across adapters

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#84]
Filing under 'juttle' as it's a cross-repo issue for adapters. Submitted by @henridf [on gitter](https://gitter.im/juttle/juttle?at=56849b1c9606b15a055e4017):

the config.json subsections are inconsistent between sqlite and elastic

specifically, the sqlite adapter has an extra layer of nesting under the property connection, while the elastic adapter places connection-related info at the top level

(i haven't looked at any other adapters)

**Comment by dmehra** [comment]
This falls under our release goal to "get to uniformity of experience" across adapters.

**Comment by dmehra** [comment]
Example of inconsistent options handling, in opentsdb adapter, trying unsupported FTS prints a long stacktrace:

```
juttle> read opentsdb -from :2016-01-01: -name "df.bytes.used" 'host'
Error: Free text search is not implemented in this context.
Unhandled rejection CompileError: Free text search is not implemented in this context.
    at Object.compileError (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/errors.js:65:12)
    at ASTVisitor.extend.visitSimpleFilterTerm (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/compiler/filters/filter-js-compiler.js:209:30)
    at Base.extend.visit (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/compiler/ast-visitor.js:111:42)
    at module.exports.compile (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle-opentsdb-adapter/lib/filter.js:11:21)
    at Juttle.proc.source.extend.addFilters (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle-opentsdb-adapter/lib/read.js:68:25)
    at Juttle.proc.source.extend.initialize (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle-opentsdb-adapter/lib/read.js:31:18)
    at Function.Extendable.extend._init_all (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/base.js:27:30)
    at Extendable.extend.constructor (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/base.js:16:14)
    at child [as constructor] (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/extendable.js:22:44)
    at child [as constructor] (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/extendable.js:22:44)
    at new child (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/extendable.js:22:44)
    at source.extend.initialize.params.adapter.on [as initialize] (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/runtime/procs/read.js:56:28)
    at Function.Extendable.extend._init_all (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/base.js:27:30)
    at Extendable.extend.constructor (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/base.js:16:14)
    at child [as constructor] (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/extendable.js:22:44)
    at child [as constructor] (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/extendable.js:22:44)
    at new child (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/extendable-base/lib/extendable.js:22:44)
    at eval (eval at <anonymous> (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/program.js:30:26), <anonymous>:4:82)
    at Base.extend._eval (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/program.js:30:32)
    at stages.eval (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/compiler/index.js:57:17)
    at /Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/lib/compiler/index.js:97:20
    at tryCatcher (/Users/dmehra/.nvm/versions/node/v4.2.4/lib/node_modules/juttle-engine/node_modules/juttle/node_modules/bluebird/js/main/util.js:26:23)
```

But trying an unsupported filter expression operator gives a nice brief error message:

```
juttle> read opentsdb -from :2016-01-01: -name "df.bytes.used" host = 'f5796f87a78f' OR mount = '/etc/hosts' | head 2
<input>:1:1: 
   1:read opentsdb -from :2016-01-01: -name "df.bytes.used" host = 'f5796f87a78f' OR mount = '/etc/hosts' | head 2
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Only AND and '=' operators with string values are supported in the optimized filter expression. (RT-TYPE-ERROR)
```

**Comment by dmajda** [comment]
Looked at this per @dmehra’s request.

>- [ ] handling of required and invalid options. Today, some inputs (such as supplying unsupported option to `read`) prints a long backtrace on the CLI, but others just print a nice error message without stack trace. The latter is preferred, of course.

Most of this should be offloaded to the base class. Note the problem is more general and also affects procs.

> - [ ] support for `-optimize false` option in `read`

Again, probably something to be put into the base class.

> apparently at least one adapter [doesn't support `-last`](https://github.com/juttle/juttle-opentsdb-adapter/issues/18) but I would have thought this is a given because base class provides it...

This is because it wasn’t converted to the new adapter API yet.

---

The blowup on FTS will be solved by the new filter API (#320), which will make it so that when you don’t write a handler for some construct, the filter containing it will be rejected gracefully (decent error with a nice message).

**Comment by dmehra** [comment]
Worth mentioning here that these documents exist on the wiki, and should be updated according to what gets decided on this ticket:
https://github.com/juttle/juttle/wiki/Adapter-Publishing-Checklist
https://github.com/juttle/juttle/wiki/Adapter-Test-Checklist
