### ISSUE TITLE
Cannot read property 'milliseconds' of undefined

### ISSUE THREAD

**Issue by henridf** [juttle/juttle#98]
The program below runs fine if I remove the `tail 1` and just pipe everything to the `write` sink.

```
$ time juttle -e "read sqlite -table 'my_table' |  put c = count() by my_field | (tail 1; write elastic -index_prefix 'gha_test' -index_interval 'none')"     
[2016-01-04 11:15:10.936] [INFO] juttle-adapter - loaded elastic
[2016-01-04 11:15:11.380] [INFO] juttle-adapter - loaded sqlite
Unhandled rejection TypeError: Cannot read property 'milliseconds' of undefined
    at /Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/tail.js:65:31
    at /Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/node_modules/underscore/underscore.js:380:19
    at Function._.map._.collect (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/node_modules/underscore/underscore.js:172:24)
    at Function._.sortBy (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/node_modules/underscore/underscore.js:376:22)
    at fanin.extend.emit_ordered_points (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/tail.js:62:24)
    at fanin.extend._run (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/tail.js:38:14)
    at fanin.extend.eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/tail.js:47:14)
    at base.extend.consume_eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/fanin.js:95:18)
    at Base.extend.emit_eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/base.js:208:25)
    at oops_fanin.extend.eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/put.js:125:14)
    at base.extend.consume_eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/fanin.js:95:18)
    at Base.extend.emit_eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle-sqlite-adapter/node_modules/juttle/lib/runtime/procs/base.js:208:25)
    at Base.extend.eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle-sqlite-adapter/node_modules/juttle/lib/runtime/procs/base.js:171:14)
    at /Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle-sqlite-adapter/node_modules/juttle-sql-adapter-common/lib/read.js:237:18
    at Object.finallyHandler (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle-sqlite-adapter/node_modules/knex/node_modules/bluebird/js/main/finally.j
```

**Comment by dmajda** [comment]
Looks like a `juttle-sql-adapter-common` bug, [moved there](https://github.com/juttle/juttle-sql-adapter-common/issues/9).
